rcv-icmp_task:
  timeout_in: 5m

  matrix:
    - freebsd_instance:
        image_family: freebsd-14-0-snap

    - freebsd_instance:
        image_family: freebsd-13-1-snap

  env:
    CIRRUS_CRON: weekly
    TEST_DIR: rcv-icmp

  install_script:
    - pkg install -y packetdrill
  always:
    test_script:
      - cd $TEST_DIR
      - sh ./run-all-rcv-icmp-tests
        #- for testcase in $(cat all-rcv-icmp-tests) ; do \
        #    testdir=$(dirname $testcase)
        #    testname=$(basename $testcase)
        #    packetdrill ${rootdir}/${testdir}/${testname}.pkt >${rootdir}/${testdir}/${testname}.out 2>&1
        #  done
